backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'journal'
    label: 'Journal'
    folder: 'content/journal'
    create: true
    slug: '{{slug}}'
    media_folder: 'static/img/uploads'
    public_folder: 'img/uploads'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'photography'
    label: 'Photography'
    folder: 'content/photography'
    create: true
    slug: '{{slug}}'
    media_folder: 'static/img/uploads'
    public_folder: 'img/uploads'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Featured Image', name: 'featuredImage', widget: 'image' }
      - { label: 'Thumbnail 1', name: 'thumbnail1', widget: 'image' }
      - { label: 'Thumbnail 2', name: 'thumbnail2', widget: 'image' }
      - { label: 'Thumbnail 3', name: 'thumbnail3', widget: 'image' }
      - { label: 'Thumbnail 4', name: 'thumbnail4', widget: 'image' }
      - { label: 'Thumbnail 5', name: 'thumbnail5', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Quote', name: 'quote', widget: 'string' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }